# Generated by Django 6.0.5 on 2026-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
